services:
  sqlite-web:
    image: coleifer/sqlite-web:latest
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/backend/data
    command: sqlite_web --host 0.0.0.0 --port 8080 /backend/data/astrology.db
    restart: unless-stopped